spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    url: jdbc:h2:file:./newsdb/news
    password: root
    user: root
  datasource:
    url: jdbc:h2:file:./newsdb/news;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE;MODE=POSTGRESQL
    password: root
    username: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true