spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    url: jdbc:h2:file:./newsdb/news
    password: root
    user: root
  datasource:
    url: jdbc:h2:file:./newsdb/news;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE;MODE=POSTGRESQL
    password: root
    username: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
request:
  uri: https://api.spaceflightnewsapi.net
  resource: /v3/articles
springdoc:
  swagger-ui:
    path: /news.html
blacklist:
  words:          #Настраиваемый черный список слов для заголовков статей. Указывать с новой строки через -, - word
threads-pool:
  size: 4         #Количество используемых потоков для ThreadPoolTaskExecutor
buffer-articles:
  limit: 4        #Лимит размера буффера для статей с каждого сайта
total-articles:
  limit: 16       #Общий лимит на скачивание статей
server:
  port: 8089